### PR TITLE
Fix up readme to look nicer on github

### PR DESCRIPTION
**Pull request by hexylena**

### CODE REVIEW

**Comment by jmchilton** [comment]
:+1:

**Comment by dannon** [comment]
Nice changes, looks good to me.

**Comment by martenson** [comment]
Let me do the honors.

**Comment by natefoo** [comment]
While I was off at class...

My only reservation, I was actually going to write it in rST because PyPI renders rST but not Markdown. And [Github does both but does not necessarily prefer either](https://gist.github.com/dupuy/1855764)

Of course, I (and most others) prefer Markdown. We could convert it to rST with pandoc when building packages for PyPI, but I didn't do that for [gravity](https://github.com/galaxyproject/gravity) so as not to add pandoc as a build-time dependency.

**Comment by hexylena** [comment]
Fair enough. I'll update the PR in a bit, I'd forgotten that publishing to PyPi was coming.

**Pull request merged**
