### PR TITLE
Support different authentication methods

### PR DESCRIPTION
**Pull request by nsoranzo**
This is a revised version of [BitBucket PR #555](https://bitbucket.org/galaxy/galaxy-central/pull-request/555/customauth-module-support/).

Initial modules:
- ActiveDirectory (LDAP)
- LocalDB (fall back to Galaxy user database)
- AlwaysReject (blacklist)

Sysadmin documentation at: https://docs.google.com/document/d/1CJp_m3vW7QKtAyBTMbE1MLgV6FAMuG3VO4HR-wHPkGk

Problems:
- still needs a yapsy egg (@jmchilton volunteered to port the code to the Galaxy plugin system)
- may interfere with ToolShed login?

Tested and approved by original author @andrewjrobinson .

### CODE REVIEW

**Comment by hexylena** [comment]
- "CustomAuth" seems to be a bit of a poor name if it's replacing the existing authn infrastructure, maybe just "auth"?

**Comment by nsoranzo** [comment]
Yes, I thought that too, but first wanted to see if it's accepted as always active.

**Comment by dannon** [comment]
I really like the idea of taking this and incorporating it into core as a general pluggable authentication framework, with localdb as the default option.

The name should change from CustomAuth to just Auth (all over), so --  lib/galaxy/customauth --> lib/galaxy/auth, etc.

The yapsy dependency should probably go at least until we make a decision on whether or not to swap _everything_ pluggable to yapsy -- we can revisit this later.  I also don't see this causing significant problems for the toolshed code (though it should still be tested).

Great work here, this is nice stuff.

**Comment by nsoranzo** [comment]
@erasche @dannon I've renamed everything from CustomAuth to Auth.

**Pull request closed without merging**
