### PR TITLE
Add missing module __init__ files that didn't make the transition to master somehow.

### PR DESCRIPTION
**Pull request by dannon**

### CODE REVIEW

**Comment by blankenberg** [comment]
:+1:

**Comment by nsoranzo** [comment]
`lib/galaxy/jobs/rules/__init__.py` (the whole `lib/galaxy/jobs/rules/` dir to be precise) is not part of master branch (yet).

Same for `lib/galaxy/tools/parser/__init__.py`, `lib/galaxy/tools/toolbox/__init__.py`, `lib/galaxy/tools/toolbox/filters/__init__.py`, `lib/galaxy/tools/toolbox/lineages/__init__.py`.

There are instead missing `__init__.py` outside of `lib`, i.e. in:

```
scripts
test/api
test/base
test/install_and_test_tool_shed_repositories/base
test/tool_shed/base
test/tool_shed/functional
test/unit/dataset_collections
test/unit/jobs
test/unit/jobs/test_rules
test/unit/tools
test/unit/workflows
```

The correct list of 52 files can be generated by:

```
$ diff -r galaxy_git_master/ galaxy_hg_stable/|grep 'Only in galaxy_hg_stable/.* __init__.py$'
```

**Comment by dannon** [comment]
D'oh!  I used the same approach but did the diff against #default.  Will update, thanks for the review.

**Comment by natefoo** [comment]
For the record, this happened due to a mistake I made while `bfg`ing removed test-data from the history after converting the hg repo to git. Full details on what I did are in [the git move trello card](https://trello.com/c/iiSBweRQ). The specific mistake is that I didn't protect the blob hashes of _all_ files in `HEAD` (only the ones in `test-data/`, and so any removed file in `test-data`'s history that matched the blob hash of a file outside `test-data` (in this case, the blob hash of an empty file) was removed (and then recommitted on `HEAD`, but that doesn't help for branches branched from older points in the history.

Another side effect I just realized is that any files in the history matching any stripped blob hashes would be stripped, even if it was outside of `test-data`. This wouldn't vanish any files that were on `HEAD` prior to running `bfg`, but would remove them from the history. That would be more difficult to protect since it means going through all commits and compiling a list of hashes for every single blob ever committed outside of `test-data` to add to the protection list.

It might be worth doing, though.

**Comment by nsoranzo** [comment]
+1, may be merged for me.

**Comment by dannon** [comment]
Just to confirm it, this fixes master but we should probably merge this branch with all other releases because they're unusable as-is.

**Comment by natefoo** [comment]
Correct, this will need to be merged with everything but dev.

+1

**Comment by nsoranzo** [comment]
Oh no, all release branches! And the list of missing files can be different in each of them.

Moreover, as Nate explained, the whole history has been affected. Maybe we can consider the nuclear option of recreating the repository, fixing also the mangled commit messages at the same time?

**Pull request merged**
